repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: '\.*conda/.*'
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '\.txt$|\.tsv$'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.json"]

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [.]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.264"
    hooks:
      - id: ruff
        args: [ --fix ]

      # mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args:
          [
            --pretty,
            --show-error-codes,
            --no-strict-optional,
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
            --check-untyped-defs,
          ]
